apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deployguard.name" . }}-api
  labels:
    {{- include "deployguard.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "deployguard.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "deployguard.labels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        {{- include "deployguard.podSecurityContext" . | nindent 8 }}
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
              name: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- include "deployguard.containerSecurityContext" . | nindent 12 }}
          startupProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
