apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-api
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000

