 version: '3.8'
 services:
   ingestion-worker:
     build: .
-    ports:
-      - "8080:8080"
+    network_mode: "host"
+    privileged: true
     restart: always
     environment:
       - ENV=production
       - PORT=8080
-      - AWS_PROFILE=production
